# Generated by Django 5.0.4 on 2024-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0003_remove_person_address_alter_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
