# Generated by Django 5.0.4 on 2024-06-10 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0004_table_end_time_table_price_table_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='end_time',
        ),
        migrations.AddField(
            model_name='table',
            name='accumulated_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='table',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
