# Generated by Django 5.0.4 on 2024-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0005_remove_table_end_time_table_accumulated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
