# Generated by Django 5.0.4 on 2024-06-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0006_alter_person_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
