# Generated by Django 5.0.4 on 2024-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0008_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
