# Generated by Django 5.0.4 on 2024-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0010_remove_table_accumulated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='rate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
