# Generated by Django 5.0.4 on 2024-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0011_table_rate_alter_table_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
