# Generated by Django 5.0.4 on 2024-06-11 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0012_alter_table_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='tabletype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApi.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='persondetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApi.person'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True),
        ),
    ]
