# Generated by Django 5.0.4 on 2024-06-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0013_remove_table_person_person_tabletype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tabletype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
