# Generated by Django 5.0.4 on 2024-06-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0015_alter_person_tabletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True),
        ),
    ]
