# Generated by Django 5.0.4 on 2024-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0017_alter_table_table_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='Frame_time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='frame',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
