# Generated by Django 5.0.4 on 2024-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0018_table_frame_time_limit_table_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='Frame_time_limit',
        ),
        migrations.AddField(
            model_name='table',
            name='frame_time_limit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
