# Generated by Django 5.0.4 on 2024-06-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0019_remove_table_frame_time_limit_table_frame_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='ac',
            field=models.BooleanField(default=False),
        ),
    ]
