# Generated by Django 5.0.4 on 2024-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0021_table_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
