# Generated by Django 5.0.4 on 2024-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0023_alter_table_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
