# Generated by Django 5.0.6 on 2024-06-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0024_alter_table_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
