# Generated by Django 5.0.6 on 2024-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0026_alter_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
