# Generated by Django 5.0.6 on 2024-06-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0027_alter_table_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='time',
        ),
    ]
