# Generated by Django 5.0.6 on 2024-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0028_remove_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
