# Generated by Django 5.0.6 on 2024-06-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0029_alter_table_table_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='ac',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='button',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='inactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
