# Generated by Django 5.0.6 on 2024-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0030_alter_table_ac_alter_table_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='button',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='inactive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
