# Generated by Django 5.0.6 on 2024-06-24 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0032_alter_table_ac_alter_table_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='frame_time_limit',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
