# Generated by Django 5.0.6 on 2024-06-24 10:27

import MyApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0033_alter_table_frame_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='frame_time_limit',
            field=models.TimeField(default=MyApi.models),
        ),
    ]
