# Generated by Django 5.0.6 on 2024-06-24 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0037_remove_table_frame_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='frame_time_limit',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
