# Generated by Django 5.0.6 on 2024-06-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0038_table_frame_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='frame_time_limit',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
