# Generated by Django 5.0.6 on 2024-06-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0044_alter_table_persondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
