# Generated by Django 5.0.6 on 2024-06-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0045_alter_person_address_alter_person_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='table',
            name='is_running',
        ),
        migrations.AddField(
            model_name='person',
            name='frame',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='tabletype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApi.table'),
        ),
    ]
