# Generated by Django 5.0.6 on 2024-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0047_rename_tabletype_person_tabletype_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tabletype_id',
            new_name='tabletype',
        ),
    ]
