# Generated by Django 5.0.6 on 2024-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0049_remove_person_is_running_table_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
