# Generated by Django 5.0.6 on 2024-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0050_person_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='frameplayed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
