# Generated by Django 5.0.6 on 2024-06-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0051_person_frameplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tabletype',
        ),
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='table',
            name='persondetail',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_type',
        ),
        migrations.AddField(
            model_name='table',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='MyApi.person'),
        ),
        migrations.AddField(
            model_name='table',
            name='tableno',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
