# Generated by Django 5.0.6 on 2024-06-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0053_table_id_alter_table_tableno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
