# Generated by Django 5.0.6 on 2024-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0055_table_perframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Perframe',
            new_name='Per_frame',
        ),
        migrations.AddField(
            model_name='table',
            name='played_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
