# Generated by Django 5.0.6 on 2024-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0056_rename_perframe_table_per_frame_table_played_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='played_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
