# Generated by Django 5.0.6 on 2024-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0057_alter_table_played_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='elapsed_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='played_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
