# Generated by Django 5.0.6 on 2024-07-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0058_table_elapsed_time_alter_table_played_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='played_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
