# Generated by Django 5.0.6 on 2024-07-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0060_table_frame_based_table_time_based'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Per_frame',
            new_name='per_frame',
        ),
    ]
