# Generated by Django 5.0.6 on 2024-07-02 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0062_table_frame_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='frame_time_limit',
        ),
    ]
