# Generated by Django 5.0.6 on 2024-07-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0063_remove_table_frame_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='played_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
