# Generated by Django 5.0.6 on 2024-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0064_person_played_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='frameplayed',
        ),
    ]
