# Generated by Django 5.0.6 on 2024-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0065_remove_person_frameplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='id',
        ),
        migrations.AlterField(
            model_name='table',
            name='tableno',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
